---
default_istio_image_tag: "0.6.0"
default_istio_namespace: "istio-system"

openshift_istio_image_dict:
  origin:
    prefix: "docker.io/openshiftistio/"
    suffix: "-centos7"
    version: "{{ default_istio_image_tag }}"
    namespace: "{{ default_istio_namespace }}"
  openshift-enterprise:
    prefix: "registry.access.redhat.com/openshift3-istio-tech-preview/"
    suffix: ""
    version: "{{ default_istio_image_tag }}"
    namespace: "{{ default_istio_namespace }}"

openshift_deployment_type: "origin"

openshift_istio_install: true
openshift_istio_install_community: false
openshift_client_binary: "/usr/bin/oc --config=/etc/origin/master/admin.kubeconfig"

addons_needing_sa:
  - "grafana"
  - "prometheus"

openshift_istio_service_accounts:
  - "istio-ca-service-account"
  - "istio-ingress-service-account"
  - "istio-mixer-service-account"
  - "istio-pilot-service-account"
  - "istio-sidecar-injector-service-account"

openshift_istio_grafana_service_account: "grafana"
openshift_istio_prometheus_service_account: "prometheus"

openshift_istio_additional_scc_service_accounts:
  - "{{ openshift_istio_grafana_service_account }}"
  - "{{ openshift_istio_prometheus_service_account }}"

openshift_istio_sidecar_service: "istio-sidecar-injector"
openshift_istio_sidecar_secret: "sidecar-injector-certs"
