---

openshift_istio_files: "roles/openshift_istio/files"

openshift_istio_yaml: "{{ openshift_istio_files }}/istio.yaml"
openshift_istio_auth_yaml: "{{ openshift_istio_files }}/istio-auth.yaml"

openshift_grafana_yaml: "{{ openshift_istio_files }}/grafana.yaml"
openshift_jaeger_production_yaml: "{{ openshift_istio_files }}/jaeger-production-template.yml"
openshift_elasticsearch_yaml: "{{ openshift_istio_files }}/elasticsearch.yml"
openshift_elasticsearch_configmap_yaml: "{{ openshift_istio_files }}/elasticsearch_configmap.yml"

launcher_template_yaml: "{{ openshift_istio_files }}/launcher-template.yaml"

openshift_istio_yaml_configuration_files:
  - "{{ openshift_istio_yaml }}"
  - "{{ openshift_istio_auth_yaml }}"

openshift_istio_jaeger_yaml_configuration_files:
  - "{{ openshift_jaeger_production_yaml }}"
