- name: Initialise prefix
  set_fact:
    openshift_istio_image_prefix: "{{ openshift_istio_image_dict[openshift_deployment_type]['prefix'] }}"
  when: openshift_istio_image_prefix is not defined

- name: Initialise suffix
  set_fact:
    openshift_istio_image_suffix: "{{ openshift_istio_image_dict[openshift_deployment_type]['suffix'] }}"
  when: openshift_istio_image_suffix is not defined

- name: Initialise version
  set_fact:
    openshift_istio_image_version: "{{ openshift_istio_image_dict[openshift_deployment_type]['version'] }}"
  when: openshift_istio_image_version is not defined

- name: Initialise Jaeger version
  set_fact:
    openshift_istio_jaeger_image_version: "{{ openshift_istio_image_dict[openshift_deployment_type]['jaeger_version'] }}"
  when: openshift_istio_jaeger_image_version is not defined or openshift_istio_jaeger_image_version == ""

- name: Initialise namespace
  set_fact:
    openshift_istio_namespace: "{{ openshift_istio_image_dict[openshift_deployment_type]['namespace'] }}"
  when: openshift_istio_namespace is not defined

- name: Initialise kiali version
  set_fact:
    openshift_istio_kiali_image_version: "{{ openshift_istio_image_dict[openshift_deployment_type]['kiali_version'] }}"
  when: openshift_istio_kiali_image_version is not defined

- name: Initialise Installation Type
  set_fact:
    openshift_istio_install_enterprise: "{{ openshift_deployment_type == 'openshift-enterprise' }}"

- name: Determine whether kiali should be installed
  set_fact:
    openshift_install_kiali: true
  when: openshift_istio_kiali_username and openshift_istio_kiali_password | bool

# Split name initialisation up into CentOS/RHEL until we have CentOS jaeger images
- name: Initialise Istio Image names when running CentOS images
  set_fact:
    openshift_istio_image_names:
      "docker.io/istio/citadel:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}citadel{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/pilot:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}pilot{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/mixer:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}mixer{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/sidecar_injector:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}sidecar-injector{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/proxy_init:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}proxy-init{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/proxy:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}proxy{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/proxyv2:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}proxyv2{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "jaegertracing/jaeger-collector:{{default_istio_jaeger_image_tag}}": "jaegertracing/jaeger-collector:{{openshift_istio_jaeger_image_version}}"
      "jaegertracing/jaeger-query:{{default_istio_jaeger_image_tag}}": "jaegertracing/jaeger-query:{{openshift_istio_jaeger_image_version}}"
      "jaegertracing/jaeger-agent:{{default_istio_jaeger_image_tag}}": "jaegertracing/jaeger-agent:{{openshift_istio_jaeger_image_version}}"
      "kiali/kiali:{{default_istio_kiali_image_tag}}": "kiali/kiali:{{openshift_istio_kiali_image_version}}"
  when: not openshift_istio_install_enterprise

- name: Initialise Istio Image names when running RHEL images
  set_fact:
    openshift_istio_image_names:
      "docker.io/istio/citadel:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}citadel{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/pilot:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}pilot{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/mixer:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}mixer{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/sidecar_injector:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}sidecar-injector{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/proxy_init:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}proxy-init{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/proxy:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}proxy{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "docker.io/istio/proxyv2:{{default_istio_image_tag}}": "{{openshift_istio_image_prefix}}proxyv2{{openshift_istio_image_suffix}}:{{openshift_istio_image_version}}"
      "jaegertracing/jaeger-collector:{{default_istio_jaeger_image_tag}}": "{{openshift_istio_image_prefix}}jaeger-collector{{openshift_istio_image_suffix}}:{{openshift_istio_jaeger_image_version}}"
      "jaegertracing/jaeger-query:{{default_istio_jaeger_image_tag}}": "{{openshift_istio_image_prefix}}jaeger-query{{openshift_istio_image_suffix}}:{{openshift_istio_jaeger_image_version}}"
      "jaegertracing/jaeger-agent:{{default_istio_jaeger_image_tag}}": "{{openshift_istio_image_prefix}}jaeger-agent{{openshift_istio_image_suffix}}:{{openshift_istio_jaeger_image_version}}"
      "kiali/kiali:{{default_istio_kiali_image_tag}}": "kiali/kiali:{{openshift_istio_kiali_image_version}}"
  when: openshift_istio_install_enterprise

- name: Initialise oc binary using master configuration
  set_fact:
    openshift_client_binary: "/usr/bin/oc --config=/etc/origin/master/admin.kubeconfig"
  when: not openshift_istio_oc_token

- name:
  command: cat /run/secrets/kubernetes.io/serviceaccount/token
  register: openshift_client_token

- name: Initialise oc binary using token
  set_fact:
    openshift_client_binary: "/usr/bin/oc --token={{ openshift_client_token.stdout }}"
  when: openshift_istio_oc_token
