---
- name: Obtain list of Mutating Webhook Configurations
  shell: "{{ openshift_client_binary }} get mutatingwebhookconfiguration -o=jsonpath='{..metadata.name}' | tr ' ' '\n' | grep istio"
  register: openshift_istio_mutatingwebhookconfiguration
  ignore_errors: true

- name: Remove Mutating Webhook
  command: "{{ openshift_client_binary }} delete mutatingwebhookconfiguration {{ item }}"
  with_items: "{{ openshift_istio_mutatingwebhookconfiguration.stdout_lines|list }}"

- name: Obtain list of Certificate Signing Requests
  shell: "{{ openshift_client_binary }} get certificatesigningrequest -o=jsonpath='{..metadata.name}' | tr ' ' '\n' | grep istio"
  register: openshift_istio_certificatesigningrequest
  ignore_errors: true

- name: Remove Certificate Signing Requests
  command: "{{ openshift_client_binary }} delete certificatesigningrequest {{ item }}"
  with_items: "{{ openshift_istio_certificatesigningrequest.stdout_lines|list }}"

- name: Obtain list of Cluster Role Bindings
  shell: "{{ openshift_client_binary }} get clusterrolebinding -o=jsonpath='{..metadata.name}' | tr ' ' '\n' | egrep 'istio|prometheus|kiali'"
  register: openshift_istio_clusterrolebinding
  ignore_errors: true

- name: Remove Cluster Role Bindings
  command: "{{ openshift_client_binary }} delete clusterrolebinding {{ item }}"
  with_items: "{{ openshift_istio_clusterrolebinding.stdout_lines|list }}"

- name: Obtain list of Cluster Roles
  shell: "{{ openshift_client_binary }} get clusterrole -o=jsonpath='{..metadata.name}' | tr ' ' '\n' | egrep 'istio|prometheus|kiali'"
  register: openshift_istio_clusterrole
  ignore_errors: true

- name: Remove Cluster Roles
  command: "{{ openshift_client_binary }} delete clusterrole {{ item }}"
  with_items: "{{ openshift_istio_clusterrole.stdout_lines|list }}"

- name: Obtain list of Custom Resource Definitions
  shell: "{{ openshift_client_binary }} get customresourcedefinition -o=jsonpath='{..metadata.name}' | tr ' ' '\n' | grep istio"
  register: openshift_istio_customresourcedefinition
  ignore_errors: true

- name: Remove Custom Resource Definitions
  command: "{{ openshift_client_binary }} delete customresourcedefinition {{ item }}"
  with_items: "{{ openshift_istio_customresourcedefinition.stdout_lines|list }}"

- name: Check istio project exists
  command: "{{ openshift_client_binary }} get namespace {{ openshift_istio_namespace }}"
  register: istio_namespace
  ignore_errors: yes

- name: Remove istio project if necessary
  command: "{{ openshift_client_binary }} delete project {{ openshift_istio_namespace }}"
  when: istio_namespace.rc == 0 and not openshift_istio_install | bool
