---
- name: Update SCC policy to allow the Istio service account {{ service_account }} to use privileged
  command: "{{ openshift_client_binary }} adm policy add-scc-to-user privileged -z {{ service_account }} -n {{ openshift_istio_namespace }}"
