---
- name: Update SCC policy to allow the Istio service account {{ service_account }} to use anyuid
  command: "{{ openshift_client_binary }} adm policy add-scc-to-user anyuid -z {{ service_account }} -n {{ openshift_istio_namespace }}"
